version: '3.1'

services:

  childrendb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
    ports:
      - 27017:27017
    volumes: 
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_URL: mongodb://root:teste@childrendb:27017

volumes: 
  mongo_data: 