version: '3'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: alex
      ME_CONFIG_BASICAUTH_PASSWORD: MongoDB@teste
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB@teste
    links:
      - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB@teste
    ports:
      - "27017:27017"
    volumes:
      - ./DataSources/Docker/Volumes/MongoDB:/data/db:rw
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge
