// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universal.EBI.Childs.API.Data;

namespace Universal.EBI.Childs.API.Migrations
{
    [DbContext(typeof(ChildDbContext))]
    [Migration("20220807201712_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChildResponsible", b =>
                {
                    b.Property<Guid>("ChildrenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsiblesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChildrenId", "ResponsiblesId");

                    b.HasIndex("ResponsiblesId");

                    b.ToTable("ChildResponsible");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("District")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PublicPlace")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique()
                        .HasFilter("[ChildId] IS NOT NULL");

                    b.HasIndex("ResponsibleId")
                        .IsUnique()
                        .HasFilter("[ResponsibleId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgeGroupType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluded")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(13)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Responsible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluded")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KinshipType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("ChildResponsible", b =>
                {
                    b.HasOne("Universal.EBI.Childs.API.Models.Child", null)
                        .WithMany()
                        .HasForeignKey("ChildrenId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Universal.EBI.Childs.API.Models.Responsible", null)
                        .WithMany()
                        .HasForeignKey("ResponsiblesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Address", b =>
                {
                    b.HasOne("Universal.EBI.Childs.API.Models.Child", "Child")
                        .WithOne("Address")
                        .HasForeignKey("Universal.EBI.Childs.API.Models.Address", "ChildId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Universal.EBI.Childs.API.Models.Responsible", "Responsible")
                        .WithOne("Address")
                        .HasForeignKey("Universal.EBI.Childs.API.Models.Address", "ResponsibleId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Child");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Child", b =>
                {
                    b.OwnsOne("Universal.EBI.Core.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ChildId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("ChildId");

                            b1.ToTable("Children");

                            b1.WithOwner()
                                .HasForeignKey("ChildId");
                        });

                    b.OwnsOne("Universal.EBI.Core.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ChildId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ChildId");

                            b1.ToTable("Children");

                            b1.WithOwner()
                                .HasForeignKey("ChildId");
                        });

                    b.Navigation("Cpf");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Phone", b =>
                {
                    b.HasOne("Universal.EBI.Childs.API.Models.Child", "Child")
                        .WithMany("Phones")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Universal.EBI.Childs.API.Models.Responsible", "Responsible")
                        .WithMany("Phones")
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Child");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Responsible", b =>
                {
                    b.OwnsOne("Universal.EBI.Core.DomainObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ResponsibleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("ResponsibleId");

                            b1.ToTable("Responsibles");

                            b1.WithOwner()
                                .HasForeignKey("ResponsibleId");
                        });

                    b.OwnsOne("Universal.EBI.Core.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ResponsibleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ResponsibleId");

                            b1.ToTable("Responsibles");

                            b1.WithOwner()
                                .HasForeignKey("ResponsibleId");
                        });

                    b.Navigation("Cpf");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Child", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Universal.EBI.Childs.API.Models.Responsible", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
